In [34]:
from sklearn import linear_model, datasets
from sklearn import tree
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from pandas.tools.plotting import scatter_matrix
from IPython.display import clear_output

In [38]:
#load Dataset
filename="E:/rt/reusablecodes/Decision Tree classification and regressions/data_banknote_authentication.txt"

#colum names for the dataset
colnames = ['Variance', 'Skewness', 'Kurtosis', 'Entropy', 'class']
#data in the file is seperated with whitespace
dataset = pd.read_csv(filename,names=colnames)

In [17]:
dataset.dtypes

Variance    float64
Skewness    float64
Kurtosis    float64
Entropy     float64
class         int64
dtype: object

In [27]:
# descriptions;summarize the distribution of each attribute.
print dataset.describe()

          Variance     Skewness     Kurtosis      Entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000


In [39]:
#checks if any column has None. Make sure None is not there
#print dataset.isnull()
#print dataset.isnull().any()
print dataset.isnull().values.any()
dataset["class"]=dataset["class"].apply(str)

dataset.dtypes

False


Variance    float64
Skewness    float64
Kurtosis    float64
Entropy     float64
class        object
dtype: object

In [40]:
#split data randomly
train_input_features,test_input_features,train_output,test_output=train_test_split(dataset[dataset.columns[0:4]],dataset[dataset.columns[4]],test_size=0.33,random_state=42)
print "dataset shape ",dataset.shape
print "train_input_features shape ",train_input_features.shape
print "train_output shape",train_output.shape
print "test_input_features shape ",test_input_features.shape
print "test_output shape",test_output.shape


dataset shape  (1372, 5)
train_input_features shape  (919, 4)
train_output shape (919L,)
test_input_features shape  (453, 4)
test_output shape (453L,)


In [41]:
#Create the model
logreg = linear_model.LogisticRegression(C=1e5)
#train_input_features & train_output are dataframes. not numpy arrays.
logreg.fit(train_input_features,train_output)            #Train the model


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [9]:
#take observation from data and see how it is predicting
print logreg.predict([[3.6216,8.6661,-2.8073,-0.44699]])

#Calculate probability for each class
print logreg.predict_proba([[3.6216,8.6661,-2.8073,-0.44699]])


[0]
[[  1.00000000e+00   2.53773403e-20]]


In [45]:
print logreg.predict(train_input_features[0:3])
print logreg.predict_proba(train_input_features[0:3])

['1' '0' '0']
[[  1.19421268e-07   9.99999881e-01]
 [  6.82741844e-01   3.17258156e-01]
 [  1.00000000e+00   1.78623741e-11]]


In [11]:
# see how it is prediting on training data
results_train=pd.DataFrame()
results_train["pred"]=logreg.predict(train_input_features)
results_train["actual"]=train_output.values

In [12]:
#see few records how it is predicting
results_train.head()

pred  actual
0     1       1
1     0       1
2     0       0
3     1       1
4     0       0

In [13]:
#calculate the accuracy using score funtion
logreg.score(train_input_features,train_output)


0.99238302502720344

In [14]:
#calculate the accuracy using score funtion
logreg.score(test_input_features,test_output)


0.99116997792494477

In [16]:
train_input_features[1:2]

Variance  Skewness  Kurtosis  Entropy
1094    2.0177    1.7982   -2.9581   0.2099

In [17]:
logreg.predict_proba(train_input_features[1:2])

array([[ 0.68274184,  0.31725816]])